check_data:
  tags:
    - pan
  script:
    # Clone MOM6-examples
    - make MOM6-examples
    # Point .datasets to archive
    - ln -s /archive/gold/datasets MOM6-examples/.datasets
    # Create/update master list of files pointed to by MOM6-examples
    - make all_files.lst
    # Make sure files are online
    - cat all_files.lst | (cd MOM6-examples/.datasets/ ; xargs dmget )
    # Checksum data pointed to by MOM6-examples
    - make md5
    # Fetch special case data
    - make special-cases
    # Download tarfiles, unpack and check md5 match
    - make test_download
